#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum DatabaseTable {
    BuyingStoreItems,
    BuyingStores,
    CartInventory,
    Char,
    CharLog,
    CharRegNum,
    CharRegStr,
    ChatLog,
    AtCommandLog,
    BranchLog,
    LoginLog,
    MvpLog,
    PickLog,
    ZenyLog,
    AccRegNum,
    AccRegStr,
    Login,
    Guild,
    GuildCastle,
    GuildMember,
    GuildPosition,
    GuildSkill,
    GuildStorage,
    Homunculus,
    Inventory,
    ItemDb,
    ItemDbRe,
    RAthenaFrItemSearch,
    Mail,
    MailAttachments,
    MobDb,
    MobDbRe,
    MobSkillDb,
    Party,
    Pet,
    Quest,
    Skill,
    Storage,
    SqlUpdates,
    VendingItems,
    Vendings,
}

impl DatabaseTable {
    pub const fn name(self) -> &'static str {
        match self {
            Self::BuyingStoreItems => "buyingstore_items",
            Self::BuyingStores => "buyingstores",
            Self::CartInventory => "cart_inventory",
            Self::Char => "char",
            Self::CharLog => "charlog",
            Self::CharRegNum => "char_reg_num",
            Self::CharRegStr => "char_reg_str",
            Self::ChatLog => "chatlog",
            Self::AtCommandLog => "atcommandlog",
            Self::BranchLog => "branchlog",
            Self::LoginLog => "loginlog",
            Self::MvpLog => "mvplog",
            Self::PickLog => "picklog",
            Self::ZenyLog => "zenylog",
            Self::AccRegNum => "acc_reg_num",
            Self::AccRegStr => "acc_reg_str",
            Self::Login => "login",
            Self::Guild => "guild",
            Self::GuildCastle => "guild_castle",
            Self::GuildMember => "guild_member",
            Self::GuildPosition => "guild_position",
            Self::GuildSkill => "guild_skill",
            Self::GuildStorage => "guild_storage",
            Self::Homunculus => "homunculus",
            Self::Inventory => "inventory",
            Self::ItemDb => "item_db",
            Self::ItemDbRe => "item_db_re",
            Self::RAthenaFrItemSearch => "rathenafr_item_search",
            Self::Mail => "mail",
            Self::MailAttachments => "mail_attachments",
            Self::MobDb => "mob_db",
            Self::MobDbRe => "mob_db_re",
            Self::MobSkillDb => "mob_skill_db",
            Self::Party => "party",
            Self::Pet => "pet",
            Self::Quest => "quest",
            Self::Skill => "skill",
            Self::Storage => "storage",
            Self::SqlUpdates => "sql_updates",
            Self::VendingItems => "vending_items",
            Self::Vendings => "vendings",
        }
    }
}
