-- rAthenaFR Discord Bot - catalogue MVP fourni
-- Executer apres rathenafr_mvp_regular_spawn.sql.
--
-- Les lignes des sources gerees par ce fichier sont remplacees a chaque
-- execution. Les entrees manual ou provenant d'une autre source sont conservees.

START TRANSACTION;

DELETE FROM `rathenafr_mvp_list`
WHERE `source` IN ('regular_spawn', 'mob_db_mvp_no_regular_spawn');

INSERT INTO `rathenafr_mvp_list` (
  `monster_id`,
  `monster_name`,
  `aegis_name`,
  `map_name`,
  `respawn_minutes`,
  `respawn_variance_minutes`,
  `enabled`,
  `source`
) VALUES
  (1038, 'Osiris', 'OSIRIS', 'moc_pryd04', 60.00, 10.00, 1, 'regular_spawn'),
  (1039, 'Baphomet', 'BAPHOMET', 'gld_dun03', 480.00, 10.00, 1, 'regular_spawn'),
  (1039, 'Baphomet', 'BAPHOMET', 'prt_maze03', 120.00, 10.00, 1, 'regular_spawn'),
  (1046, 'Doppelganger', 'DOPPELGANGER', 'gef_dun02', 120.00, 10.00, 1, 'regular_spawn'),
  (1046, 'Doppelganger', 'DOPPELGANGER', 'gld_dun04', 480.00, 10.00, 1, 'regular_spawn'),
  (1059, 'Mistress', 'MISTRESS', 'gld_dun02', 480.00, 10.00, 1, 'regular_spawn'),
  (1059, 'Mistress', 'MISTRESS', 'mjolnir_04', 120.00, 10.00, 1, 'regular_spawn'),
  (1086, 'Golden Thief Bug', 'GOLDEN_BUG', 'prt_sewb4', 60.00, 10.00, 1, 'regular_spawn'),
  (1087, 'Orc Hero', 'ORK_HERO', 'gef_fild03', 60.00, 10.00, 1, 'regular_spawn'),
  (1112, 'Drake', 'DRAKE', 'treasure02', 120.00, 10.00, 1, 'regular_spawn'),
  (1115, 'Eddga', 'EDDGA', 'gld_dun01_2', 480.00, 10.00, 1, 'regular_spawn'),
  (1115, 'Eddga', 'EDDGA', 'pay_fild10', 120.00, 10.00, 1, 'regular_spawn'),
  (1147, 'Maya', 'MAYA', 'anthell02', 120.00, 10.00, 1, 'regular_spawn'),
  (1147, 'Maya', 'MAYA', 'gld_dun02_2', 480.00, 10.00, 1, 'regular_spawn'),
  (1150, 'Moonlight Flower', 'MOONLIGHT', 'gld_dun01', 480.00, 10.00, 1, 'regular_spawn'),
  (1150, 'Moonlight Flower', 'MOONLIGHT', 'pay_dun04', 60.00, 10.00, 1, 'regular_spawn'),
  (1157, 'Pharaoh', 'PHARAOH', 'in_sphinx5', 60.00, 10.00, 1, 'regular_spawn'),
  (1159, 'Phreeoni', 'PHREEONI', 'moc_fild17', 120.00, 10.00, 1, 'regular_spawn'),
  (1190, 'Orc Lord', 'ORC_LORD', 'gef_fild10', 120.00, 10.00, 1, 'regular_spawn'),
  (1251, 'Stormy Knight', 'KNIGHT_OF_WINDSTORM', 'xmas_dun02', 60.00, 10.00, 1, 'regular_spawn'),
  (1252, 'Hatii', 'GARM', 'xmas_fild01', 120.00, 10.00, 1, 'regular_spawn'),
  (1272, 'Dark Lord', 'DARK_LORD', 'gl_chyard', 60.00, 10.00, 1, 'regular_spawn'),
  (1272, 'Dark Lord', 'DARK_LORD', 'gl_chyard_', 60.00, 10.00, 1, 'regular_spawn'),
  (1272, 'Dark Lord', 'DARK_LORD', 'gld_dun04_2', 480.00, 10.00, 1, 'regular_spawn'),
  (1312, 'Turtle General', 'TURTLE_GENERAL', 'tur_dun04', 60.00, 10.00, 1, 'regular_spawn'),
  (1373, 'Lord of the Dead', 'LORD_OF_DEATH', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1389, 'Dracula', 'DRACULA', 'gef_dun01', 60.00, 10.00, 1, 'regular_spawn'),
  (1399, 'Baphomet', 'EVENT_BAPHO', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1418, 'Evil Snake Lord', 'DARK_SNAKE_LORD', 'gon_dun03', 94.17, 10.00, 1, 'regular_spawn'),
  (1492, 'Samurai Specter', 'INCANTATION_SAMURAI', 'ama_dun03', 91.00, 10.00, 1, 'regular_spawn'),
  (1502, 'Bring it on!', 'PORING_V', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1511, 'Amon Ra', 'AMON_RA', 'moc_pryd06', 60.00, 10.00, 1, 'regular_spawn'),
  (1518, 'White Lady', 'BACSOJIN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1583, 'Tao Gunka', 'TAO_GUNKA', 'beach_dun', 300.00, 10.00, 1, 'regular_spawn'),
  (1623, 'RSX-0806', 'RSX_0806', 'ein_dun02', 125.00, 10.00, 1, 'regular_spawn'),
  (1630, 'White Lady', 'BACSOJIN_', 'lou_dun03', 116.67, 10.00, 1, 'regular_spawn'),
  (1646, 'Lord Knight Seyren', 'B_SEYREN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1647, 'Assassin Cross Eremes', 'B_EREMES', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1648, 'Whitesmith Howard', 'B_HARWORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1649, 'High Priest Margaretha', 'B_MAGALETA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1650, 'Sniper Cecil', 'B_SHECIL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1651, 'High Wizard Kathryne', 'B_KATRINN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1658, 'Egnigem Cenia', 'B_YGNIZEM', 'lhz_dun02', 120.00, 10.00, 1, 'regular_spawn'),
  (1685, 'Vesper', 'APOCALIPS_H', 'jupe_core', 120.00, 10.00, 1, 'regular_spawn'),
  (1688, 'Lady Tanee', 'LADY_TANEE', 'ayo_dun02', 420.00, 10.00, 1, 'regular_spawn'),
  (1708, 'Thanatos Phantom', 'THANATOS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1719, 'Detardeurus', 'DETALE', 'abyss_03', 180.00, 10.00, 1, 'regular_spawn'),
  (1734, 'Kiel D-01', 'KIEL_', 'kh_dun02', 120.00, 10.00, 1, 'regular_spawn'),
  (1751, 'Valkyrie Randgris', 'RANDGRIS', 'odin_tem03', 480.00, 10.00, 1, 'regular_spawn'),
  (1766, 'Angeling', 'EM_ANGELING', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1767, 'Deviling', 'EM_DEVILING', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1768, 'Gloom Under Night', 'GLOOMUNDERNIGHT', 'ra_san05', 300.00, 10.00, 1, 'regular_spawn'),
  (1779, 'Ktullanux', 'KTULLANUX', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1785, 'Atroce', 'ATROCE', 'gld_dun03_2', 480.00, 10.00, 1, 'regular_spawn'),
  (1785, 'Atroce', 'ATROCE', 'ra_fild03', 180.00, 10.00, 1, 'regular_spawn'),
  (1785, 'Atroce', 'ATROCE', 'ra_fild04', 300.00, 10.00, 1, 'regular_spawn'),
  (1785, 'Atroce', 'ATROCE', 've_fild01', 180.00, 10.00, 1, 'regular_spawn'),
  (1785, 'Atroce', 'ATROCE', 've_fild02', 360.00, 10.00, 1, 'regular_spawn'),
  (1813, 'Hydrolancer', 'EVENT_HYDRO', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1817, 'Detardeurus', 'EVENT_DETALE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1832, 'Ifrit', 'IFRIT', 'thor_v03', 660.00, 10.00, 1, 'regular_spawn'),
  (1871, 'Falling Bishop', 'FALLINGBISHOP', 'abbey02', 120.00, 10.00, 1, 'regular_spawn'),
  (1874, 'Beelzebub', 'BEELZEBUB_', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1876, 'Lord of the Dead', 'E_LORD_OF_DEATH', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1885, 'Gopinich', 'GOPINICH', 'mosk_dun03', 120.00, 10.00, 1, 'regular_spawn'),
  (1917, 'Wounded Morocc', 'MOROCC_', 'moc_fild22', 720.00, 10.00, 1, 'regular_spawn'),
  (1956, 'Naght Sieger', 'NAGHT_SIEGER', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1957, 'Entweihen Crothen', 'ENTWEIHEN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (1980, 'Kublin', 'KUBLIN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2022, 'Nidhoggur''s Shadow', 'S_NYDHOG', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2052, 'Dark Lord', 'E_DARKLORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2068, 'Boitata', 'BOITATA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2075, 'Ragunta', 'E_VADON_X', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2087, 'Scaraba Queen', 'QUEEN_SCARABA', 'dic_dun02', 120.00, 0.00, 1, 'regular_spawn'),
  (2094, 'Orc Hero', 'E_ORK_HERO2', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2095, 'Eddga', 'E_EDDGA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2096, 'Osiris', 'E_OSIRIS2', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2097, 'Dracula', 'E_DRACULA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2098, 'Doppelganger', 'E_DOPPELGANGER', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2099, 'Mistress', 'E_MISTRESS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2100, 'Baphomet', 'E_BAPHOMET2', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2101, 'Lord of the Dead', 'E_LORD_OF_DEATH2', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2102, 'Dark Lord', 'E_DARK_LORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2103, 'Ktullanux', 'E_KTULLANUX', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2104, 'Evil Snake Lord', 'E_DARK_SNAKE_LORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2105, 'Turtle General', 'E_TURTLE_GENERAL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2106, 'Vesper', 'E_APOCALIPS_H', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2107, 'Fallen Bishop Hibram', 'E_FALLINGBISHOP', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2108, 'Gloom Under Night', 'E_GLOOMUNDERNIGHT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2109, 'Valkyrie Randgris', 'E_RANDGRIS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2110, 'Ifrit', 'E_IFRIT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2111, 'Whitesmith Howard', 'E_B_HARWORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2112, 'Lord Knight Seyren', 'E_B_SEYREN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2113, 'Assassin Cross Eremes', 'E_B_EREMES', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2131, 'Lost Dragon', 'LOST_DRAGON', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2156, 'Leak', 'LEAK', 'dew_dun01', 120.00, 0.00, 1, 'regular_spawn'),
  (2165, 'Gold Queen Scaraba', 'I_QUEEN_SCARABA', 'dic_dun03', 120.00, 0.00, 1, 'regular_spawn'),
  (2187, 'Gloomy Coelacanth', 'COELACANTH_N_A', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2188, 'Weird Coelacanth', 'COELACANTH_N_M', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2189, 'Mutant Coelacanth', 'COELACANTH_H_M', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2190, 'Violent Coelacanth', 'COELACANTH_H_A', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2194, 'Giant Octopus', 'MD_GIANT_OCTOPUS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2202, 'Kraken', 'KRAKEN', 'iz_dun05', 120.00, 30.00, 1, 'regular_spawn'),
  (2212, 'Stormy Knight', 'E_KNIGHT_OF_WINDSTORM', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2235, 'Paladin Randel', 'B_RANDEL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2236, 'Creator Flamel', 'B_FLAMEL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2237, 'Professor Celia', 'B_CELIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2238, 'Champion Chen', 'B_CHEN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2239, 'Stalker Gertie', 'B_GERTIE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2240, 'Clown Alphoccio', 'B_ALPHOCCIO', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2241, 'Gypsy Trentini', 'B_TRENTINI', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2249, 'Angry Student Pyuriel', 'PYURIEL', 'gld2_prt', 480.00, 10.00, 1, 'regular_spawn'),
  (2251, 'Gioia', 'GIOIA', 'gld2_ald', 480.00, 10.00, 1, 'regular_spawn'),
  (2253, 'General Daehyun', 'DAEHYON', 'gld2_pay', 480.00, 10.00, 1, 'regular_spawn'),
  (2255, 'Dark Guardian Kades', 'KADES', 'gld2_gef', 480.00, 10.00, 1, 'regular_spawn'),
  (2306, 'Golden Thief Bug', 'E_GOLDEN_BUG', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2319, 'Buwaya', 'BUWAYA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2341, '2011 RWC Boss', 'RWC_BOSS2011', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2352, 'RSX 0805', 'E_RSX_0805', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2362, 'Amon Ra (Nightmare)', 'N_AMON_RA', 'moc_prydn2', 60.00, 10.00, 1, 'regular_spawn'),
  (2441, 'The Last One', 'B_NOVICE', 'teg_dun01', 480.00, 0.00, 1, 'regular_spawn'),
  (2442, 'King of the Alley', 'B_SUPERNOVICE', 'teg_dun02', 120.00, 0.00, 1, 'regular_spawn'),
  (2475, 'Corrupted Soul', 'MG_CORRUPTION_ROOT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2476, 'Amdarais', 'MG_AMDARAIS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2483, 'Nightmare Baphomet', 'NG_BAPHOMET', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2529, 'Faceworm Queen', 'FACEWORM_QUEEN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2532, 'Red Faceworm Queen', 'FACEWORM_QUEEN_R', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2533, 'Green Faceworm Queen', 'FACEWORM_QUEEN_G', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2534, 'Blue Faceworm Queen', 'FACEWORM_QUEEN_B', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2535, 'Yellow Faceworm Queen', 'FACEWORM_QUEEN_Y', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2564, 'Fenrir', 'GEFFEN_FENRIR', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2942, 'Evil Fanatics', 'MM_EVIL_FANATICS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (2996, 'Celine Kimi', 'XM_CELINE_KIMI', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3000, 'Morocc Necromancer', 'EP14_MORS_BOSSB', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3029, 'Reaper Yanku', 'GRIM_REAPER_ANKOU', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3073, 'Awakened Ferre', 'GRAND_PERE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3074, 'Time Holder', 'TIMEHOLDER', 'c_tower3_', 120.00, 0.00, 1, 'regular_spawn'),
  (3097, 'Despair God Morroc', 'MM_MOROCC_ADT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3124, 'Charleston 3', 'CHARLESTON3', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3181, 'Captain Ferlock', 'E1_FELOCK', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3190, 'Sarah Irene', 'MM_SARAH', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3220, 'Guillotine Cross Eremes', 'V_B_EREMES', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3221, 'Arch Bishop Margaretha', 'V_B_MAGALETA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3222, 'Ranger Cecil', 'V_B_SHECIL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3223, 'Mechanic Howard', 'V_B_HARWORD', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3224, 'Warlock Kathryne', 'V_B_KATRINN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3225, 'Rune Knight Seyren', 'V_B_SEYREN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3240, 'Royal Guard Randel', 'V_B_RANDEL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3241, 'Genetic Flamel', 'V_B_FLAMEL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3242, 'Sorcerer Celia', 'V_B_CELIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3243, 'Sura Chen', 'V_B_CHEN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3244, 'Shadow Chaser Gertie', 'V_B_GERTIE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3245, 'Minstrel Alphoccio', 'V_B_ALPHOCCIO', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3246, 'Wanderer Trentini', 'V_B_TRENTINI', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3254, 'T_W_O', 'T_W_O', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3426, 'Infinite Eddga', 'MIN_EDDGA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3427, 'Infinite Osiris', 'MIN_OSIRIS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3428, 'Infinite Phreeoni', 'MIN_PHREEONI', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3429, 'Infinite Orc Hero', 'MIN_ORK_HERO', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3430, 'Infinite Tao Gunka', 'MIN_TAO_GUNKA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3450, 'Bijou', 'BIJOU', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3473, 'Stefan.J.E.Wolf', 'AS_RAGGED_GOLEM', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3505, 'Big Eggring', 'DR_BIG_EGGRING', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3621, 'Pet Child', 'EP16_2_MM_CUTIE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3628, 'Heart Hunter Ebel', 'EP16_2_H_HUNTER_EV', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3633, 'Venomous Chimera', 'EP16_2_VENOM_KIMERA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3658, 'Lich Lord', 'MD_LICH_LORD_100', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3659, 'Lich Lord', 'MD_LICH_LORD_160', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3741, 'Spider Chariot', 'MECHASPIDER', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3757, 'Dracula of Rage', 'ILL_DRACULA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3758, 'Angry Moonlight Flower', 'ILL_MOONLIGHT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3796, 'Awakened Ktullanux', 'ILL_KTULLANUX', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3804, 'Ominous Turtle General', 'ILL_TURTLE_GENERAL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (3810, 'King Poring', 'MD_KING_PORING', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20273, 'Ancient Tao Gunka', 'ILL_TAO_GUNKA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20277, 'Ancient Wootan Defender', 'ILL_WOOTAN_DEFENDER', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20340, 'EL1-A17T', 'MD_EL_A17T', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20346, 'Miguel', 'MD_MIGUEL', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20381, 'R48-85-Bestia', 'EP17_1_R4885_BESTIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20419, 'Rigid Muspellskoll', 'MUSPELLSKOLL_H', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20421, 'Corrupted Spider Queen', 'BRINARANEA_H', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20422, 'Corrupted Dark Lord', 'DARK_LORD_H', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20601, 'Jewel Ungoliant', 'JUNGOLIANT', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20620, 'Red Pepper', 'MD_REDPEPPER', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20621, 'Senior Red Pepper', 'MD_REDPEPPER_H', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20642, 'Sweety', 'MD_SWEETY', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20648, 'Boss Meow', 'EP17_2_PITAYA_BOSS', 'ba_lost', 120.00, 10.00, 1, 'regular_spawn'),
  (20659, 'Pitaya Boss', 'MD_PITAYA_BOSS', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20667, 'Silva Papilia', 'MD_SILVA_PAPILIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20668, 'Gran Papilia', 'MD_GRAN_PAPILIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20811, 'Deep Sea Kraken', 'ILL_KRAKEN', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20843, 'Deep Sea Witch', 'ILL_ABYSMAL_WITCH', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20928, 'The One', 'CHIMERA_THEONE', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20934, 'R001-Bestia', 'R001_BESTIA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (20943, 'Death Witch', 'DEATH_WITCH', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21301, 'Burning Fang', 'EP18_BURNING_FANG', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21314, 'Schulang', 'EP18_MD_SCHULANG', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21316, 'Schulang', 'EP18_MD_SCHULANG_R', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21317, 'Twisted God Freyja', 'EP18_MD_DEMI_FREYJA_R', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21360, 'Schulang', 'EP18_MD_SCHULANG_L', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21361, 'Twisted God Freyja', 'EP18_MD_DEMI_FREYJA_L', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn'),
  (21395, 'Silent Maya', 'ILL_MAYA', NULL, NULL, NULL, 1, 'mob_db_mvp_no_regular_spawn');

COMMIT;
