name: Publication

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Construire les artefacts de release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rathenafr-discord-bot-linux-x86_64
            binary_path: target/release/rathenafr-discord-bot
          - os: windows-latest
            artifact_name: rathenafr-discord-bot-windows-x86_64.exe
            binary_path: target/release/rathenafr-discord-bot.exe

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v6

      - name: Installer la toolchain Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Mettre en cache Cargo et target
        uses: Swatinem/rust-cache@v2
        env:
          NODE_OPTIONS: --no-deprecation

      - name: Construire le binaire de release
        run: cargo build --release

      - name: Préparer l’artefact sous Linux
        if: runner.os != 'Windows'
        run: cp "${{ matrix.binary_path }}" "${{ matrix.artifact_name }}"

      - name: Préparer l’artefact sous Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: Copy-Item "${{ matrix.binary_path }}" "${{ matrix.artifact_name }}"

      - name: Envoyer l’artefact de build
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  github-release:
    name: Publier la release GitHub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Télécharger les artefacts
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Publier la release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/**
          generate_release_notes: true
